### PR TITLE
fix: change return type from certificate to consent

### LINKED ISSUE #64: Change json return type after validate a data
We decided to add a `Consent` data type in panacea-core. After validating a data, the oracles need to return `Certificate`, which includes `UnsignedCertificate` and `Signature`. So, the provider could submit a consent with json file returned from validate request.

I'll change after the [PR](https://github.com/medibloc/panacea-core/pull/590) merged.

### PR DESCRIPTION
**Pull request by inchori**
Closes #64

### CODE REVIEW

File: server/service/datadeal/handler_data_validation.go [hunk 1]
```diff
@@ -150,11 +150,15 @@ func (s *dataDealService) ValidateData(w http.ResponseWriter, r *http.Request) {
...
-	payload := datadealtypes.Certificate{
+	certificate := &datadealtypes.Certificate{
 		UnsignedCertificate: unsignedDataCert,
 		Signature:           sig.Serialize(),
 	}
 
+	payload := datadealtypes.Consent{
+		Certificate: certificate,
+	}
+
```
Comment (H4NLee) [inline server/service/datadeal/handler_data_validation.go:161]: As @youngjoon-lee said in offline channel, oracle will just return the certificate, and provider will make consent to provide the data with this certificate.
So, let's just return the certificate itself

Comment (inchori) [reply server/service/datadeal/handler_data_validation.go:161]: Yes, when I tested this code and seller request validating a data, this API returns like this:
```json
{
    "certificate": {
        "unsigned_certificate": {
            "cid": "...",
            "unique_id": "...",
            "oracle_address": "...",
            "deal_id": 1,
            "provider_address": "...",
            "data_hash": "..."
        },
        "signature": "..."
    }
}
```
Because consent includes a certificate, so would I need to change it?

**Review by gyuguen — APPROVED** [review]
LGTM

File: server/service/datadeal/handler_data_validation.go (hunk 1 above)
Comment (H4NLee) [reply server/service/datadeal/handler_data_validation.go:170]: Yes it includes certificate. I just wanna say that returning consent and returning certificate are distinctly different.

For example, in the future, let's assume that we add a expiration for the consent (how long the provider provide the data).
Then, the provider will get a certificate from oracle, and make consent message to provide data with expiration he/she want. Making the consent is the provider's job.

Comment (inchori) [reply server/service/datadeal/handler_data_validation.go]: As we discussed in offline, we will be rollback. I understand the @H4NLee's comment. And I think that it is correct.
Fixed in [d3e313e](https://github.com/medibloc/panacea-oracle/pull/67/commits/d3e313e3f72e142337ffde989b26522d03553a64).

**Review by H4NLee — APPROVED** [review]
lgtm

File: server/service/datadeal/handler_data_validation.go (hunk 1 above)
Comment (gyuguen) [reply server/service/datadeal/handler_data_validation.go]: Good. I agree. 
Thank you!

**Review by gyuguen — APPROVED** [review]

**Review by youngjoon-lee — APPROVED** [review]
ㅣㅎ스
